// Code generated by ent, DO NOT EDIT.

package tweet

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the tweet type in the database.
	Label = "tweet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldScreenName holds the string denoting the screen_name field in the database.
	FieldScreenName = "screen_name"
	// FieldFullText holds the string denoting the full_text field in the database.
	FieldFullText = "full_text"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldPermanentURL holds the string denoting the permanent_url field in the database.
	FieldPermanentURL = "permanent_url"
	// FieldRawJSON holds the string denoting the raw_json field in the database.
	FieldRawJSON = "raw_json"
	// FieldSyncedAt holds the string denoting the synced_at field in the database.
	FieldSyncedAt = "synced_at"
	// FieldBookmarked holds the string denoting the bookmarked field in the database.
	FieldBookmarked = "bookmarked"
	// FieldRating holds the string denoting the rating field in the database.
	FieldRating = "rating"
	// EdgeMedia holds the string denoting the media edge name in mutations.
	EdgeMedia = "media"
	// Table holds the table name of the tweet in the database.
	Table = "tweets"
	// MediaTable is the table that holds the media relation/edge.
	MediaTable = "media"
	// MediaInverseTable is the table name for the Media entity.
	// It exists in this package in order to avoid circular dependency with the "media" package.
	MediaInverseTable = "media"
	// MediaColumn is the table column denoting the media relation/edge.
	MediaColumn = "tweet_id"
)

// Columns holds all SQL columns for tweet fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldScreenName,
	FieldFullText,
	FieldCreatedAt,
	FieldPermanentURL,
	FieldRawJSON,
	FieldSyncedAt,
	FieldBookmarked,
	FieldRating,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultRating holds the default value on creation for the "rating" field.
	DefaultRating int8
	// RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	RatingValidator func(int8) error
)

// Bookmarked defines the type for the "bookmarked" enum field.
type Bookmarked string

// Bookmarked values.
const (
	BookmarkedYes      Bookmarked = "yes"
	BookmarkedFormerly Bookmarked = "formerly"
	BookmarkedNo       Bookmarked = "no"
)

func (b Bookmarked) String() string {
	return string(b)
}

// BookmarkedValidator is a validator for the "bookmarked" field enum values. It is called by the builders before save.
func BookmarkedValidator(b Bookmarked) error {
	switch b {
	case BookmarkedYes, BookmarkedFormerly, BookmarkedNo:
		return nil
	default:
		return fmt.Errorf("tweet: invalid enum value for bookmarked field: %q", b)
	}
}

// OrderOption defines the ordering options for the Tweet queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByScreenName orders the results by the screen_name field.
func ByScreenName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScreenName, opts...).ToFunc()
}

// ByFullText orders the results by the full_text field.
func ByFullText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFullText, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByPermanentURL orders the results by the permanent_url field.
func ByPermanentURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPermanentURL, opts...).ToFunc()
}

// ByRawJSON orders the results by the raw_json field.
func ByRawJSON(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRawJSON, opts...).ToFunc()
}

// BySyncedAt orders the results by the synced_at field.
func BySyncedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSyncedAt, opts...).ToFunc()
}

// ByBookmarked orders the results by the bookmarked field.
func ByBookmarked(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBookmarked, opts...).ToFunc()
}

// ByRating orders the results by the rating field.
func ByRating(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRating, opts...).ToFunc()
}

// ByMediaCount orders the results by media count.
func ByMediaCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMediaStep(), opts...)
	}
}

// ByMedia orders the results by media terms.
func ByMedia(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMediaStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMediaStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MediaInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MediaTable, MediaColumn),
	)
}
