// Code generated by ent, DO NOT EDIT.

package tweet

import (
	"time"
	"twitter-bookmarks-downloader/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldName, v))
}

// ScreenName applies equality check predicate on the "screen_name" field. It's identical to ScreenNameEQ.
func ScreenName(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldScreenName, v))
}

// FullText applies equality check predicate on the "full_text" field. It's identical to FullTextEQ.
func FullText(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldFullText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldCreatedAt, v))
}

// PermanentURL applies equality check predicate on the "permanent_url" field. It's identical to PermanentURLEQ.
func PermanentURL(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldPermanentURL, v))
}

// RawJSON applies equality check predicate on the "raw_json" field. It's identical to RawJSONEQ.
func RawJSON(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldRawJSON, v))
}

// SyncedAt applies equality check predicate on the "synced_at" field. It's identical to SyncedAtEQ.
func SyncedAt(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldSyncedAt, v))
}

// Rating applies equality check predicate on the "rating" field. It's identical to RatingEQ.
func Rating(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldRating, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldName, v))
}

// ScreenNameEQ applies the EQ predicate on the "screen_name" field.
func ScreenNameEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldScreenName, v))
}

// ScreenNameNEQ applies the NEQ predicate on the "screen_name" field.
func ScreenNameNEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldScreenName, v))
}

// ScreenNameIn applies the In predicate on the "screen_name" field.
func ScreenNameIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldScreenName, vs...))
}

// ScreenNameNotIn applies the NotIn predicate on the "screen_name" field.
func ScreenNameNotIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldScreenName, vs...))
}

// ScreenNameGT applies the GT predicate on the "screen_name" field.
func ScreenNameGT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldScreenName, v))
}

// ScreenNameGTE applies the GTE predicate on the "screen_name" field.
func ScreenNameGTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldScreenName, v))
}

// ScreenNameLT applies the LT predicate on the "screen_name" field.
func ScreenNameLT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldScreenName, v))
}

// ScreenNameLTE applies the LTE predicate on the "screen_name" field.
func ScreenNameLTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldScreenName, v))
}

// ScreenNameContains applies the Contains predicate on the "screen_name" field.
func ScreenNameContains(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContains(FieldScreenName, v))
}

// ScreenNameHasPrefix applies the HasPrefix predicate on the "screen_name" field.
func ScreenNameHasPrefix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasPrefix(FieldScreenName, v))
}

// ScreenNameHasSuffix applies the HasSuffix predicate on the "screen_name" field.
func ScreenNameHasSuffix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasSuffix(FieldScreenName, v))
}

// ScreenNameEqualFold applies the EqualFold predicate on the "screen_name" field.
func ScreenNameEqualFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldScreenName, v))
}

// ScreenNameContainsFold applies the ContainsFold predicate on the "screen_name" field.
func ScreenNameContainsFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldScreenName, v))
}

// FullTextEQ applies the EQ predicate on the "full_text" field.
func FullTextEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldFullText, v))
}

// FullTextNEQ applies the NEQ predicate on the "full_text" field.
func FullTextNEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldFullText, v))
}

// FullTextIn applies the In predicate on the "full_text" field.
func FullTextIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldFullText, vs...))
}

// FullTextNotIn applies the NotIn predicate on the "full_text" field.
func FullTextNotIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldFullText, vs...))
}

// FullTextGT applies the GT predicate on the "full_text" field.
func FullTextGT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldFullText, v))
}

// FullTextGTE applies the GTE predicate on the "full_text" field.
func FullTextGTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldFullText, v))
}

// FullTextLT applies the LT predicate on the "full_text" field.
func FullTextLT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldFullText, v))
}

// FullTextLTE applies the LTE predicate on the "full_text" field.
func FullTextLTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldFullText, v))
}

// FullTextContains applies the Contains predicate on the "full_text" field.
func FullTextContains(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContains(FieldFullText, v))
}

// FullTextHasPrefix applies the HasPrefix predicate on the "full_text" field.
func FullTextHasPrefix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasPrefix(FieldFullText, v))
}

// FullTextHasSuffix applies the HasSuffix predicate on the "full_text" field.
func FullTextHasSuffix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasSuffix(FieldFullText, v))
}

// FullTextEqualFold applies the EqualFold predicate on the "full_text" field.
func FullTextEqualFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldFullText, v))
}

// FullTextContainsFold applies the ContainsFold predicate on the "full_text" field.
func FullTextContainsFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldFullText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldCreatedAt, v))
}

// PermanentURLEQ applies the EQ predicate on the "permanent_url" field.
func PermanentURLEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldPermanentURL, v))
}

// PermanentURLNEQ applies the NEQ predicate on the "permanent_url" field.
func PermanentURLNEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldPermanentURL, v))
}

// PermanentURLIn applies the In predicate on the "permanent_url" field.
func PermanentURLIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldPermanentURL, vs...))
}

// PermanentURLNotIn applies the NotIn predicate on the "permanent_url" field.
func PermanentURLNotIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldPermanentURL, vs...))
}

// PermanentURLGT applies the GT predicate on the "permanent_url" field.
func PermanentURLGT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldPermanentURL, v))
}

// PermanentURLGTE applies the GTE predicate on the "permanent_url" field.
func PermanentURLGTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldPermanentURL, v))
}

// PermanentURLLT applies the LT predicate on the "permanent_url" field.
func PermanentURLLT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldPermanentURL, v))
}

// PermanentURLLTE applies the LTE predicate on the "permanent_url" field.
func PermanentURLLTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldPermanentURL, v))
}

// PermanentURLContains applies the Contains predicate on the "permanent_url" field.
func PermanentURLContains(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContains(FieldPermanentURL, v))
}

// PermanentURLHasPrefix applies the HasPrefix predicate on the "permanent_url" field.
func PermanentURLHasPrefix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasPrefix(FieldPermanentURL, v))
}

// PermanentURLHasSuffix applies the HasSuffix predicate on the "permanent_url" field.
func PermanentURLHasSuffix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasSuffix(FieldPermanentURL, v))
}

// PermanentURLEqualFold applies the EqualFold predicate on the "permanent_url" field.
func PermanentURLEqualFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldPermanentURL, v))
}

// PermanentURLContainsFold applies the ContainsFold predicate on the "permanent_url" field.
func PermanentURLContainsFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldPermanentURL, v))
}

// RawJSONEQ applies the EQ predicate on the "raw_json" field.
func RawJSONEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldRawJSON, v))
}

// RawJSONNEQ applies the NEQ predicate on the "raw_json" field.
func RawJSONNEQ(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldRawJSON, v))
}

// RawJSONIn applies the In predicate on the "raw_json" field.
func RawJSONIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldRawJSON, vs...))
}

// RawJSONNotIn applies the NotIn predicate on the "raw_json" field.
func RawJSONNotIn(vs ...string) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldRawJSON, vs...))
}

// RawJSONGT applies the GT predicate on the "raw_json" field.
func RawJSONGT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldRawJSON, v))
}

// RawJSONGTE applies the GTE predicate on the "raw_json" field.
func RawJSONGTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldRawJSON, v))
}

// RawJSONLT applies the LT predicate on the "raw_json" field.
func RawJSONLT(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldRawJSON, v))
}

// RawJSONLTE applies the LTE predicate on the "raw_json" field.
func RawJSONLTE(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldRawJSON, v))
}

// RawJSONContains applies the Contains predicate on the "raw_json" field.
func RawJSONContains(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContains(FieldRawJSON, v))
}

// RawJSONHasPrefix applies the HasPrefix predicate on the "raw_json" field.
func RawJSONHasPrefix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasPrefix(FieldRawJSON, v))
}

// RawJSONHasSuffix applies the HasSuffix predicate on the "raw_json" field.
func RawJSONHasSuffix(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldHasSuffix(FieldRawJSON, v))
}

// RawJSONEqualFold applies the EqualFold predicate on the "raw_json" field.
func RawJSONEqualFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldEqualFold(FieldRawJSON, v))
}

// RawJSONContainsFold applies the ContainsFold predicate on the "raw_json" field.
func RawJSONContainsFold(v string) predicate.Tweet {
	return predicate.Tweet(sql.FieldContainsFold(FieldRawJSON, v))
}

// SyncedAtEQ applies the EQ predicate on the "synced_at" field.
func SyncedAtEQ(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldSyncedAt, v))
}

// SyncedAtNEQ applies the NEQ predicate on the "synced_at" field.
func SyncedAtNEQ(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldSyncedAt, v))
}

// SyncedAtIn applies the In predicate on the "synced_at" field.
func SyncedAtIn(vs ...time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldSyncedAt, vs...))
}

// SyncedAtNotIn applies the NotIn predicate on the "synced_at" field.
func SyncedAtNotIn(vs ...time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldSyncedAt, vs...))
}

// SyncedAtGT applies the GT predicate on the "synced_at" field.
func SyncedAtGT(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldSyncedAt, v))
}

// SyncedAtGTE applies the GTE predicate on the "synced_at" field.
func SyncedAtGTE(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldSyncedAt, v))
}

// SyncedAtLT applies the LT predicate on the "synced_at" field.
func SyncedAtLT(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldSyncedAt, v))
}

// SyncedAtLTE applies the LTE predicate on the "synced_at" field.
func SyncedAtLTE(v time.Time) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldSyncedAt, v))
}

// BookmarkedEQ applies the EQ predicate on the "bookmarked" field.
func BookmarkedEQ(v Bookmarked) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldBookmarked, v))
}

// BookmarkedNEQ applies the NEQ predicate on the "bookmarked" field.
func BookmarkedNEQ(v Bookmarked) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldBookmarked, v))
}

// BookmarkedIn applies the In predicate on the "bookmarked" field.
func BookmarkedIn(vs ...Bookmarked) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldBookmarked, vs...))
}

// BookmarkedNotIn applies the NotIn predicate on the "bookmarked" field.
func BookmarkedNotIn(vs ...Bookmarked) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldBookmarked, vs...))
}

// RatingEQ applies the EQ predicate on the "rating" field.
func RatingEQ(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldEQ(FieldRating, v))
}

// RatingNEQ applies the NEQ predicate on the "rating" field.
func RatingNEQ(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldNEQ(FieldRating, v))
}

// RatingIn applies the In predicate on the "rating" field.
func RatingIn(vs ...int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldIn(FieldRating, vs...))
}

// RatingNotIn applies the NotIn predicate on the "rating" field.
func RatingNotIn(vs ...int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldNotIn(FieldRating, vs...))
}

// RatingGT applies the GT predicate on the "rating" field.
func RatingGT(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldGT(FieldRating, v))
}

// RatingGTE applies the GTE predicate on the "rating" field.
func RatingGTE(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldGTE(FieldRating, v))
}

// RatingLT applies the LT predicate on the "rating" field.
func RatingLT(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldLT(FieldRating, v))
}

// RatingLTE applies the LTE predicate on the "rating" field.
func RatingLTE(v int8) predicate.Tweet {
	return predicate.Tweet(sql.FieldLTE(FieldRating, v))
}

// HasMedia applies the HasEdge predicate on the "media" edge.
func HasMedia() predicate.Tweet {
	return predicate.Tweet(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MediaTable, MediaColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMediaWith applies the HasEdge predicate on the "media" edge with a given conditions (other predicates).
func HasMediaWith(preds ...predicate.Media) predicate.Tweet {
	return predicate.Tweet(func(s *sql.Selector) {
		step := newMediaStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tweet) predicate.Tweet {
	return predicate.Tweet(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tweet) predicate.Tweet {
	return predicate.Tweet(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tweet) predicate.Tweet {
	return predicate.Tweet(sql.NotPredicates(p))
}
