// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "media_id", Type: field.TypeString},
		{Name: "position", Type: field.TypeInt, Default: 0},
		{Name: "url", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "downloaded", Type: field.TypeBool, Default: false},
		{Name: "failed", Type: field.TypeBool, Default: false},
		{Name: "retry_count", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "tweet_id", Type: field.TypeString},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "media_tweets_media",
				Columns:    []*schema.Column{MediaColumns[10]},
				RefColumns: []*schema.Column{TweetsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "media_tweet_id",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[10]},
			},
			{
				Name:    "media_media_id",
				Unique:  false,
				Columns: []*schema.Column{MediaColumns[1]},
			},
		},
	}
	// TweetsColumns holds the columns for the "tweets" table.
	TweetsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "screen_name", Type: field.TypeString},
		{Name: "full_text", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "permanent_url", Type: field.TypeString},
		{Name: "raw_json", Type: field.TypeString},
		{Name: "synced_at", Type: field.TypeTime},
		{Name: "bookmarked", Type: field.TypeEnum, Enums: []string{"yes", "formerly", "no"}},
		{Name: "rating", Type: field.TypeInt8, Default: 0},
	}
	// TweetsTable holds the schema information for the "tweets" table.
	TweetsTable = &schema.Table{
		Name:       "tweets",
		Columns:    TweetsColumns,
		PrimaryKey: []*schema.Column{TweetsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaTable,
		TweetsTable,
	}
)

func init() {
	MediaTable.ForeignKeys[0].RefTable = TweetsTable
	TweetsTable.Annotation = &entsql.Annotation{}
	TweetsTable.Annotation.Checks = map[string]string{
		"bookmarked_valid": "`bookmarked` IN ('yes', 'formerly', 'no')",
		"rating_range":     "`rating` BETWEEN -1 AND 5",
	}
}
