// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaCreate is the builder for creating a Media entity.
type MediaCreate struct {
	config
	mutation *MediaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTweetID sets the "tweet_id" field.
func (_c *MediaCreate) SetTweetID(v string) *MediaCreate {
	_c.mutation.SetTweetID(v)
	return _c
}

// SetMediaID sets the "media_id" field.
func (_c *MediaCreate) SetMediaID(v string) *MediaCreate {
	_c.mutation.SetMediaID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *MediaCreate) SetPosition(v int) *MediaCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *MediaCreate) SetNillablePosition(v *int) *MediaCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MediaCreate) SetURL(v string) *MediaCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MediaCreate) SetType(v string) *MediaCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetDownloaded sets the "downloaded" field.
func (_c *MediaCreate) SetDownloaded(v bool) *MediaCreate {
	_c.mutation.SetDownloaded(v)
	return _c
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_c *MediaCreate) SetNillableDownloaded(v *bool) *MediaCreate {
	if v != nil {
		_c.SetDownloaded(*v)
	}
	return _c
}

// SetFailed sets the "failed" field.
func (_c *MediaCreate) SetFailed(v bool) *MediaCreate {
	_c.mutation.SetFailed(v)
	return _c
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_c *MediaCreate) SetNillableFailed(v *bool) *MediaCreate {
	if v != nil {
		_c.SetFailed(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *MediaCreate) SetRetryCount(v int) *MediaCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *MediaCreate) SetNillableRetryCount(v *int) *MediaCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaCreate) SetCreatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableCreatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaCreate) SetUpdatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableUpdatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaCreate) SetID(v string) *MediaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_c *MediaCreate) SetTweet(v *Tweet) *MediaCreate {
	return _c.SetTweetID(v.ID)
}

// Mutation returns the MediaMutation object of the builder.
func (_c *MediaCreate) Mutation() *MediaMutation {
	return _c.mutation
}

// Save creates the Media in the database.
func (_c *MediaCreate) Save(ctx context.Context) (*Media, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaCreate) SaveX(ctx context.Context) *Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaCreate) defaults() {
	if _, ok := _c.mutation.Position(); !ok {
		v := media.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.Downloaded(); !ok {
		v := media.DefaultDownloaded
		_c.mutation.SetDownloaded(v)
	}
	if _, ok := _c.mutation.Failed(); !ok {
		v := media.DefaultFailed
		_c.mutation.SetFailed(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := media.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := media.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := media.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaCreate) check() error {
	if _, ok := _c.mutation.TweetID(); !ok {
		return &ValidationError{Name: "tweet_id", err: errors.New(`ent: missing required field "Media.tweet_id"`)}
	}
	if _, ok := _c.mutation.MediaID(); !ok {
		return &ValidationError{Name: "media_id", err: errors.New(`ent: missing required field "Media.media_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Media.position"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Media.url"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Media.type"`)}
	}
	if _, ok := _c.mutation.Downloaded(); !ok {
		return &ValidationError{Name: "downloaded", err: errors.New(`ent: missing required field "Media.downloaded"`)}
	}
	if _, ok := _c.mutation.Failed(); !ok {
		return &ValidationError{Name: "failed", err: errors.New(`ent: missing required field "Media.failed"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "Media.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Media.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Media.updated_at"`)}
	}
	if len(_c.mutation.TweetIDs()) == 0 {
		return &ValidationError{Name: "tweet", err: errors.New(`ent: missing required edge "Media.tweet"`)}
	}
	return nil
}

func (_c *MediaCreate) sqlSave(ctx context.Context) (*Media, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Media.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaCreate) createSpec() (*Media, *sqlgraph.CreateSpec) {
	var (
		_node = &Media{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(media.Table, sqlgraph.NewFieldSpec(media.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.MediaID(); ok {
		_spec.SetField(media.FieldMediaID, field.TypeString, value)
		_node.MediaID = value
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(media.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(media.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Downloaded(); ok {
		_spec.SetField(media.FieldDownloaded, field.TypeBool, value)
		_node.Downloaded = value
	}
	if value, ok := _c.mutation.Failed(); ok {
		_spec.SetField(media.FieldFailed, field.TypeBool, value)
		_node.Failed = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(media.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TweetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TweetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Media.Create().
//		SetTweetID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaUpsert) {
//			SetTweetID(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaCreate) OnConflict(opts ...sql.ConflictOption) *MediaUpsertOne {
	_c.conflict = opts
	return &MediaUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Media.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaCreate) OnConflictColumns(columns ...string) *MediaUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaUpsertOne{
		create: _c,
	}
}

type (
	// MediaUpsertOne is the builder for "upsert"-ing
	//  one Media node.
	MediaUpsertOne struct {
		create *MediaCreate
	}

	// MediaUpsert is the "OnConflict" setter.
	MediaUpsert struct {
		*sql.UpdateSet
	}
)

// SetTweetID sets the "tweet_id" field.
func (u *MediaUpsert) SetTweetID(v string) *MediaUpsert {
	u.Set(media.FieldTweetID, v)
	return u
}

// UpdateTweetID sets the "tweet_id" field to the value that was provided on create.
func (u *MediaUpsert) UpdateTweetID() *MediaUpsert {
	u.SetExcluded(media.FieldTweetID)
	return u
}

// SetMediaID sets the "media_id" field.
func (u *MediaUpsert) SetMediaID(v string) *MediaUpsert {
	u.Set(media.FieldMediaID, v)
	return u
}

// UpdateMediaID sets the "media_id" field to the value that was provided on create.
func (u *MediaUpsert) UpdateMediaID() *MediaUpsert {
	u.SetExcluded(media.FieldMediaID)
	return u
}

// SetPosition sets the "position" field.
func (u *MediaUpsert) SetPosition(v int) *MediaUpsert {
	u.Set(media.FieldPosition, v)
	return u
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *MediaUpsert) UpdatePosition() *MediaUpsert {
	u.SetExcluded(media.FieldPosition)
	return u
}

// AddPosition adds v to the "position" field.
func (u *MediaUpsert) AddPosition(v int) *MediaUpsert {
	u.Add(media.FieldPosition, v)
	return u
}

// SetURL sets the "url" field.
func (u *MediaUpsert) SetURL(v string) *MediaUpsert {
	u.Set(media.FieldURL, v)
	return u
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MediaUpsert) UpdateURL() *MediaUpsert {
	u.SetExcluded(media.FieldURL)
	return u
}

// SetType sets the "type" field.
func (u *MediaUpsert) SetType(v string) *MediaUpsert {
	u.Set(media.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MediaUpsert) UpdateType() *MediaUpsert {
	u.SetExcluded(media.FieldType)
	return u
}

// SetDownloaded sets the "downloaded" field.
func (u *MediaUpsert) SetDownloaded(v bool) *MediaUpsert {
	u.Set(media.FieldDownloaded, v)
	return u
}

// UpdateDownloaded sets the "downloaded" field to the value that was provided on create.
func (u *MediaUpsert) UpdateDownloaded() *MediaUpsert {
	u.SetExcluded(media.FieldDownloaded)
	return u
}

// SetFailed sets the "failed" field.
func (u *MediaUpsert) SetFailed(v bool) *MediaUpsert {
	u.Set(media.FieldFailed, v)
	return u
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *MediaUpsert) UpdateFailed() *MediaUpsert {
	u.SetExcluded(media.FieldFailed)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *MediaUpsert) SetRetryCount(v int) *MediaUpsert {
	u.Set(media.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *MediaUpsert) UpdateRetryCount() *MediaUpsert {
	u.SetExcluded(media.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *MediaUpsert) AddRetryCount(v int) *MediaUpsert {
	u.Add(media.FieldRetryCount, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaUpsert) SetUpdatedAt(v time.Time) *MediaUpsert {
	u.Set(media.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaUpsert) UpdateUpdatedAt() *MediaUpsert {
	u.SetExcluded(media.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Media.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(media.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MediaUpsertOne) UpdateNewValues() *MediaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(media.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(media.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Media.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MediaUpsertOne) Ignore() *MediaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaUpsertOne) DoNothing() *MediaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaCreate.OnConflict
// documentation for more info.
func (u *MediaUpsertOne) Update(set func(*MediaUpsert)) *MediaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaUpsert{UpdateSet: update})
	}))
	return u
}

// SetTweetID sets the "tweet_id" field.
func (u *MediaUpsertOne) SetTweetID(v string) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetTweetID(v)
	})
}

// UpdateTweetID sets the "tweet_id" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateTweetID() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateTweetID()
	})
}

// SetMediaID sets the "media_id" field.
func (u *MediaUpsertOne) SetMediaID(v string) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetMediaID(v)
	})
}

// UpdateMediaID sets the "media_id" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateMediaID() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateMediaID()
	})
}

// SetPosition sets the "position" field.
func (u *MediaUpsertOne) SetPosition(v int) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *MediaUpsertOne) AddPosition(v int) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdatePosition() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdatePosition()
	})
}

// SetURL sets the "url" field.
func (u *MediaUpsertOne) SetURL(v string) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateURL() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateURL()
	})
}

// SetType sets the "type" field.
func (u *MediaUpsertOne) SetType(v string) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateType() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateType()
	})
}

// SetDownloaded sets the "downloaded" field.
func (u *MediaUpsertOne) SetDownloaded(v bool) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetDownloaded(v)
	})
}

// UpdateDownloaded sets the "downloaded" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateDownloaded() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateDownloaded()
	})
}

// SetFailed sets the "failed" field.
func (u *MediaUpsertOne) SetFailed(v bool) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateFailed() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateFailed()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *MediaUpsertOne) SetRetryCount(v int) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *MediaUpsertOne) AddRetryCount(v int) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateRetryCount() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateRetryCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaUpsertOne) SetUpdatedAt(v time.Time) *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaUpsertOne) UpdateUpdatedAt() *MediaUpsertOne {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MediaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MediaUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: MediaUpsertOne.ID is not supported by MySQL driver. Use MediaUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MediaUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MediaCreateBulk is the builder for creating many Media entities in bulk.
type MediaCreateBulk struct {
	config
	err      error
	builders []*MediaCreate
	conflict []sql.ConflictOption
}

// Save creates the Media entities in the database.
func (_c *MediaCreateBulk) Save(ctx context.Context) ([]*Media, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Media, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaCreateBulk) SaveX(ctx context.Context) []*Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Media.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MediaUpsert) {
//			SetTweetID(v+v).
//		}).
//		Exec(ctx)
func (_c *MediaCreateBulk) OnConflict(opts ...sql.ConflictOption) *MediaUpsertBulk {
	_c.conflict = opts
	return &MediaUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Media.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MediaCreateBulk) OnConflictColumns(columns ...string) *MediaUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MediaUpsertBulk{
		create: _c,
	}
}

// MediaUpsertBulk is the builder for "upsert"-ing
// a bulk of Media nodes.
type MediaUpsertBulk struct {
	create *MediaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Media.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(media.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *MediaUpsertBulk) UpdateNewValues() *MediaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(media.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(media.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Media.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MediaUpsertBulk) Ignore() *MediaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MediaUpsertBulk) DoNothing() *MediaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MediaCreateBulk.OnConflict
// documentation for more info.
func (u *MediaUpsertBulk) Update(set func(*MediaUpsert)) *MediaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MediaUpsert{UpdateSet: update})
	}))
	return u
}

// SetTweetID sets the "tweet_id" field.
func (u *MediaUpsertBulk) SetTweetID(v string) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetTweetID(v)
	})
}

// UpdateTweetID sets the "tweet_id" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateTweetID() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateTweetID()
	})
}

// SetMediaID sets the "media_id" field.
func (u *MediaUpsertBulk) SetMediaID(v string) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetMediaID(v)
	})
}

// UpdateMediaID sets the "media_id" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateMediaID() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateMediaID()
	})
}

// SetPosition sets the "position" field.
func (u *MediaUpsertBulk) SetPosition(v int) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetPosition(v)
	})
}

// AddPosition adds v to the "position" field.
func (u *MediaUpsertBulk) AddPosition(v int) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.AddPosition(v)
	})
}

// UpdatePosition sets the "position" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdatePosition() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdatePosition()
	})
}

// SetURL sets the "url" field.
func (u *MediaUpsertBulk) SetURL(v string) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetURL(v)
	})
}

// UpdateURL sets the "url" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateURL() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateURL()
	})
}

// SetType sets the "type" field.
func (u *MediaUpsertBulk) SetType(v string) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateType() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateType()
	})
}

// SetDownloaded sets the "downloaded" field.
func (u *MediaUpsertBulk) SetDownloaded(v bool) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetDownloaded(v)
	})
}

// UpdateDownloaded sets the "downloaded" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateDownloaded() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateDownloaded()
	})
}

// SetFailed sets the "failed" field.
func (u *MediaUpsertBulk) SetFailed(v bool) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetFailed(v)
	})
}

// UpdateFailed sets the "failed" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateFailed() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateFailed()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *MediaUpsertBulk) SetRetryCount(v int) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *MediaUpsertBulk) AddRetryCount(v int) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateRetryCount() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateRetryCount()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MediaUpsertBulk) SetUpdatedAt(v time.Time) *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MediaUpsertBulk) UpdateUpdatedAt() *MediaUpsertBulk {
	return u.Update(func(s *MediaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *MediaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MediaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MediaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MediaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
