// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaCreate is the builder for creating a Media entity.
type MediaCreate struct {
	config
	mutation *MediaMutation
	hooks    []Hook
}

// SetTweetID sets the "tweet_id" field.
func (_c *MediaCreate) SetTweetID(v string) *MediaCreate {
	_c.mutation.SetTweetID(v)
	return _c
}

// SetPosition sets the "position" field.
func (_c *MediaCreate) SetPosition(v int) *MediaCreate {
	_c.mutation.SetPosition(v)
	return _c
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_c *MediaCreate) SetNillablePosition(v *int) *MediaCreate {
	if v != nil {
		_c.SetPosition(*v)
	}
	return _c
}

// SetURL sets the "url" field.
func (_c *MediaCreate) SetURL(v string) *MediaCreate {
	_c.mutation.SetURL(v)
	return _c
}

// SetType sets the "type" field.
func (_c *MediaCreate) SetType(v string) *MediaCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetDownloaded sets the "downloaded" field.
func (_c *MediaCreate) SetDownloaded(v bool) *MediaCreate {
	_c.mutation.SetDownloaded(v)
	return _c
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_c *MediaCreate) SetNillableDownloaded(v *bool) *MediaCreate {
	if v != nil {
		_c.SetDownloaded(*v)
	}
	return _c
}

// SetFailed sets the "failed" field.
func (_c *MediaCreate) SetFailed(v bool) *MediaCreate {
	_c.mutation.SetFailed(v)
	return _c
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_c *MediaCreate) SetNillableFailed(v *bool) *MediaCreate {
	if v != nil {
		_c.SetFailed(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *MediaCreate) SetRetryCount(v int) *MediaCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *MediaCreate) SetNillableRetryCount(v *int) *MediaCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MediaCreate) SetCreatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableCreatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MediaCreate) SetUpdatedAt(v time.Time) *MediaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MediaCreate) SetNillableUpdatedAt(v *time.Time) *MediaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MediaCreate) SetID(v string) *MediaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_c *MediaCreate) SetTweet(v *Tweet) *MediaCreate {
	return _c.SetTweetID(v.ID)
}

// Mutation returns the MediaMutation object of the builder.
func (_c *MediaCreate) Mutation() *MediaMutation {
	return _c.mutation
}

// Save creates the Media in the database.
func (_c *MediaCreate) Save(ctx context.Context) (*Media, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MediaCreate) SaveX(ctx context.Context) *Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MediaCreate) defaults() {
	if _, ok := _c.mutation.Position(); !ok {
		v := media.DefaultPosition
		_c.mutation.SetPosition(v)
	}
	if _, ok := _c.mutation.Downloaded(); !ok {
		v := media.DefaultDownloaded
		_c.mutation.SetDownloaded(v)
	}
	if _, ok := _c.mutation.Failed(); !ok {
		v := media.DefaultFailed
		_c.mutation.SetFailed(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := media.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := media.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := media.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MediaCreate) check() error {
	if _, ok := _c.mutation.TweetID(); !ok {
		return &ValidationError{Name: "tweet_id", err: errors.New(`ent: missing required field "Media.tweet_id"`)}
	}
	if _, ok := _c.mutation.Position(); !ok {
		return &ValidationError{Name: "position", err: errors.New(`ent: missing required field "Media.position"`)}
	}
	if _, ok := _c.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Media.url"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Media.type"`)}
	}
	if _, ok := _c.mutation.Downloaded(); !ok {
		return &ValidationError{Name: "downloaded", err: errors.New(`ent: missing required field "Media.downloaded"`)}
	}
	if _, ok := _c.mutation.Failed(); !ok {
		return &ValidationError{Name: "failed", err: errors.New(`ent: missing required field "Media.failed"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "Media.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Media.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Media.updated_at"`)}
	}
	if len(_c.mutation.TweetIDs()) == 0 {
		return &ValidationError{Name: "tweet", err: errors.New(`ent: missing required edge "Media.tweet"`)}
	}
	return nil
}

func (_c *MediaCreate) sqlSave(ctx context.Context) (*Media, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Media.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MediaCreate) createSpec() (*Media, *sqlgraph.CreateSpec) {
	var (
		_node = &Media{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(media.Table, sqlgraph.NewFieldSpec(media.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Position(); ok {
		_spec.SetField(media.FieldPosition, field.TypeInt, value)
		_node.Position = value
	}
	if value, ok := _c.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(media.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Downloaded(); ok {
		_spec.SetField(media.FieldDownloaded, field.TypeBool, value)
		_node.Downloaded = value
	}
	if value, ok := _c.mutation.Failed(); ok {
		_spec.SetField(media.FieldFailed, field.TypeBool, value)
		_node.Failed = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(media.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.TweetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TweetID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MediaCreateBulk is the builder for creating many Media entities in bulk.
type MediaCreateBulk struct {
	config
	err      error
	builders []*MediaCreate
}

// Save creates the Media entities in the database.
func (_c *MediaCreateBulk) Save(ctx context.Context) ([]*Media, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Media, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MediaCreateBulk) SaveX(ctx context.Context) []*Media {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MediaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MediaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
