// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/predicate"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks    []Hook
	mutation *MediaMutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTweetID sets the "tweet_id" field.
func (_u *MediaUpdate) SetTweetID(v string) *MediaUpdate {
	_u.mutation.SetTweetID(v)
	return _u
}

// SetNillableTweetID sets the "tweet_id" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableTweetID(v *string) *MediaUpdate {
	if v != nil {
		_u.SetTweetID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *MediaUpdate) SetPosition(v int) *MediaUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *MediaUpdate) SetNillablePosition(v *int) *MediaUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *MediaUpdate) AddPosition(v int) *MediaUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaUpdate) SetURL(v string) *MediaUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableURL(v *string) *MediaUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MediaUpdate) SetType(v string) *MediaUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableType(v *string) *MediaUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDownloaded sets the "downloaded" field.
func (_u *MediaUpdate) SetDownloaded(v bool) *MediaUpdate {
	_u.mutation.SetDownloaded(v)
	return _u
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableDownloaded(v *bool) *MediaUpdate {
	if v != nil {
		_u.SetDownloaded(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *MediaUpdate) SetFailed(v bool) *MediaUpdate {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableFailed(v *bool) *MediaUpdate {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *MediaUpdate) SetRetryCount(v int) *MediaUpdate {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *MediaUpdate) SetNillableRetryCount(v *int) *MediaUpdate {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *MediaUpdate) AddRetryCount(v int) *MediaUpdate {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdate) SetUpdatedAt(v time.Time) *MediaUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_u *MediaUpdate) SetTweet(v *Tweet) *MediaUpdate {
	return _u.SetTweetID(v.ID)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdate) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearTweet clears the "tweet" edge to the Tweet entity.
func (_u *MediaUpdate) ClearTweet() *MediaUpdate {
	_u.mutation.ClearTweet()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MediaUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MediaUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdate) check() error {
	if _u.mutation.TweetCleared() && len(_u.mutation.TweetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Media.tweet"`)
	}
	return nil
}

func (_u *MediaUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(media.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(media.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(media.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Downloaded(); ok {
		_spec.SetField(media.FieldDownloaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(media.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(media.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(media.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TweetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaMutation
}

// SetTweetID sets the "tweet_id" field.
func (_u *MediaUpdateOne) SetTweetID(v string) *MediaUpdateOne {
	_u.mutation.SetTweetID(v)
	return _u
}

// SetNillableTweetID sets the "tweet_id" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableTweetID(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetTweetID(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *MediaUpdateOne) SetPosition(v int) *MediaUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillablePosition(v *int) *MediaUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *MediaUpdateOne) AddPosition(v int) *MediaUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetURL sets the "url" field.
func (_u *MediaUpdateOne) SetURL(v string) *MediaUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableURL(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *MediaUpdateOne) SetType(v string) *MediaUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableType(v *string) *MediaUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetDownloaded sets the "downloaded" field.
func (_u *MediaUpdateOne) SetDownloaded(v bool) *MediaUpdateOne {
	_u.mutation.SetDownloaded(v)
	return _u
}

// SetNillableDownloaded sets the "downloaded" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableDownloaded(v *bool) *MediaUpdateOne {
	if v != nil {
		_u.SetDownloaded(*v)
	}
	return _u
}

// SetFailed sets the "failed" field.
func (_u *MediaUpdateOne) SetFailed(v bool) *MediaUpdateOne {
	_u.mutation.SetFailed(v)
	return _u
}

// SetNillableFailed sets the "failed" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableFailed(v *bool) *MediaUpdateOne {
	if v != nil {
		_u.SetFailed(*v)
	}
	return _u
}

// SetRetryCount sets the "retry_count" field.
func (_u *MediaUpdateOne) SetRetryCount(v int) *MediaUpdateOne {
	_u.mutation.ResetRetryCount()
	_u.mutation.SetRetryCount(v)
	return _u
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_u *MediaUpdateOne) SetNillableRetryCount(v *int) *MediaUpdateOne {
	if v != nil {
		_u.SetRetryCount(*v)
	}
	return _u
}

// AddRetryCount adds value to the "retry_count" field.
func (_u *MediaUpdateOne) AddRetryCount(v int) *MediaUpdateOne {
	_u.mutation.AddRetryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MediaUpdateOne) SetUpdatedAt(v time.Time) *MediaUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTweet sets the "tweet" edge to the Tweet entity.
func (_u *MediaUpdateOne) SetTweet(v *Tweet) *MediaUpdateOne {
	return _u.SetTweetID(v.ID)
}

// Mutation returns the MediaMutation object of the builder.
func (_u *MediaUpdateOne) Mutation() *MediaMutation {
	return _u.mutation
}

// ClearTweet clears the "tweet" edge to the Tweet entity.
func (_u *MediaUpdateOne) ClearTweet() *MediaUpdateOne {
	_u.mutation.ClearTweet()
	return _u
}

// Where appends a list predicates to the MediaUpdate builder.
func (_u *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Media entity.
func (_u *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MediaUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := media.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MediaUpdateOne) check() error {
	if _u.mutation.TweetCleared() && len(_u.mutation.TweetIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Media.tweet"`)
	}
	return nil
}

func (_u *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(media.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(media.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(media.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Downloaded(); ok {
		_spec.SetField(media.FieldDownloaded, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Failed(); ok {
		_spec.SetField(media.FieldFailed, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RetryCount(); ok {
		_spec.SetField(media.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRetryCount(); ok {
		_spec.AddField(media.FieldRetryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(media.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.TweetCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TweetIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   media.TweetTable,
			Columns: []string{media.TweetColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Media{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
