// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/schema"
	"twitter-bookmarks-downloader/ent/tweet"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescPosition is the schema descriptor for position field.
	mediaDescPosition := mediaFields[3].Descriptor()
	// media.DefaultPosition holds the default value on creation for the position field.
	media.DefaultPosition = mediaDescPosition.Default.(int)
	// mediaDescDownloaded is the schema descriptor for downloaded field.
	mediaDescDownloaded := mediaFields[6].Descriptor()
	// media.DefaultDownloaded holds the default value on creation for the downloaded field.
	media.DefaultDownloaded = mediaDescDownloaded.Default.(bool)
	// mediaDescFailed is the schema descriptor for failed field.
	mediaDescFailed := mediaFields[7].Descriptor()
	// media.DefaultFailed holds the default value on creation for the failed field.
	media.DefaultFailed = mediaDescFailed.Default.(bool)
	// mediaDescRetryCount is the schema descriptor for retry_count field.
	mediaDescRetryCount := mediaFields[8].Descriptor()
	// media.DefaultRetryCount holds the default value on creation for the retry_count field.
	media.DefaultRetryCount = mediaDescRetryCount.Default.(int)
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaFields[9].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescUpdatedAt is the schema descriptor for updated_at field.
	mediaDescUpdatedAt := mediaFields[10].Descriptor()
	// media.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	media.DefaultUpdatedAt = mediaDescUpdatedAt.Default.(func() time.Time)
	// media.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	media.UpdateDefaultUpdatedAt = mediaDescUpdatedAt.UpdateDefault.(func() time.Time)
	tweetFields := schema.Tweet{}.Fields()
	_ = tweetFields
	// tweetDescRating is the schema descriptor for rating field.
	tweetDescRating := tweetFields[9].Descriptor()
	// tweet.DefaultRating holds the default value on creation for the rating field.
	tweet.DefaultRating = tweetDescRating.Default.(int8)
	// tweet.RatingValidator is a validator for the "rating" field. It is called by the builders before save.
	tweet.RatingValidator = func() func(int8) error {
		validators := tweetDescRating.Validators
		fns := [...]func(int8) error{
			validators[0].(func(int8) error),
			validators[1].(func(int8) error),
		}
		return func(rating int8) error {
			for _, fn := range fns {
				if err := fn(rating); err != nil {
					return err
				}
			}
			return nil
		}
	}()
}
