// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TweetCreate is the builder for creating a Tweet entity.
type TweetCreate struct {
	config
	mutation *TweetMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *TweetCreate) SetName(v string) *TweetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetScreenName sets the "screen_name" field.
func (_c *TweetCreate) SetScreenName(v string) *TweetCreate {
	_c.mutation.SetScreenName(v)
	return _c
}

// SetFullText sets the "full_text" field.
func (_c *TweetCreate) SetFullText(v string) *TweetCreate {
	_c.mutation.SetFullText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TweetCreate) SetCreatedAt(v time.Time) *TweetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetPermanentURL sets the "permanent_url" field.
func (_c *TweetCreate) SetPermanentURL(v string) *TweetCreate {
	_c.mutation.SetPermanentURL(v)
	return _c
}

// SetRawJSON sets the "raw_json" field.
func (_c *TweetCreate) SetRawJSON(v string) *TweetCreate {
	_c.mutation.SetRawJSON(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *TweetCreate) SetSyncedAt(v time.Time) *TweetCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetBookmarked sets the "bookmarked" field.
func (_c *TweetCreate) SetBookmarked(v tweet.Bookmarked) *TweetCreate {
	_c.mutation.SetBookmarked(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *TweetCreate) SetRating(v int8) *TweetCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *TweetCreate) SetNillableRating(v *int8) *TweetCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TweetCreate) SetID(v string) *TweetCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_c *TweetCreate) AddMediumIDs(ids ...string) *TweetCreate {
	_c.mutation.AddMediumIDs(ids...)
	return _c
}

// AddMedia adds the "media" edges to the Media entity.
func (_c *TweetCreate) AddMedia(v ...*Media) *TweetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediumIDs(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_c *TweetCreate) Mutation() *TweetMutation {
	return _c.mutation
}

// Save creates the Tweet in the database.
func (_c *TweetCreate) Save(ctx context.Context) (*Tweet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TweetCreate) SaveX(ctx context.Context) *Tweet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TweetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TweetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TweetCreate) defaults() {
	if _, ok := _c.mutation.Rating(); !ok {
		v := tweet.DefaultRating
		_c.mutation.SetRating(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TweetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tweet.name"`)}
	}
	if _, ok := _c.mutation.ScreenName(); !ok {
		return &ValidationError{Name: "screen_name", err: errors.New(`ent: missing required field "Tweet.screen_name"`)}
	}
	if _, ok := _c.mutation.FullText(); !ok {
		return &ValidationError{Name: "full_text", err: errors.New(`ent: missing required field "Tweet.full_text"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tweet.created_at"`)}
	}
	if _, ok := _c.mutation.PermanentURL(); !ok {
		return &ValidationError{Name: "permanent_url", err: errors.New(`ent: missing required field "Tweet.permanent_url"`)}
	}
	if _, ok := _c.mutation.RawJSON(); !ok {
		return &ValidationError{Name: "raw_json", err: errors.New(`ent: missing required field "Tweet.raw_json"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "Tweet.synced_at"`)}
	}
	if _, ok := _c.mutation.Bookmarked(); !ok {
		return &ValidationError{Name: "bookmarked", err: errors.New(`ent: missing required field "Tweet.bookmarked"`)}
	}
	if v, ok := _c.mutation.Bookmarked(); ok {
		if err := tweet.BookmarkedValidator(v); err != nil {
			return &ValidationError{Name: "bookmarked", err: fmt.Errorf(`ent: validator failed for field "Tweet.bookmarked": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Tweet.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := tweet.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Tweet.rating": %w`, err)}
		}
	}
	return nil
}

func (_c *TweetCreate) sqlSave(ctx context.Context) (*Tweet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tweet.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TweetCreate) createSpec() (*Tweet, *sqlgraph.CreateSpec) {
	var (
		_node = &Tweet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tweet.Table, sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tweet.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ScreenName(); ok {
		_spec.SetField(tweet.FieldScreenName, field.TypeString, value)
		_node.ScreenName = value
	}
	if value, ok := _c.mutation.FullText(); ok {
		_spec.SetField(tweet.FieldFullText, field.TypeString, value)
		_node.FullText = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tweet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PermanentURL(); ok {
		_spec.SetField(tweet.FieldPermanentURL, field.TypeString, value)
		_node.PermanentURL = value
	}
	if value, ok := _c.mutation.RawJSON(); ok {
		_spec.SetField(tweet.FieldRawJSON, field.TypeString, value)
		_node.RawJSON = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(tweet.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.Bookmarked(); ok {
		_spec.SetField(tweet.FieldBookmarked, field.TypeEnum, value)
		_node.Bookmarked = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(tweet.FieldRating, field.TypeInt8, value)
		_node.Rating = value
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TweetCreateBulk is the builder for creating many Tweet entities in bulk.
type TweetCreateBulk struct {
	config
	err      error
	builders []*TweetCreate
}

// Save creates the Tweet entities in the database.
func (_c *TweetCreateBulk) Save(ctx context.Context) ([]*Tweet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tweet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TweetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TweetCreateBulk) SaveX(ctx context.Context) []*Tweet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TweetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TweetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
