// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TweetCreate is the builder for creating a Tweet entity.
type TweetCreate struct {
	config
	mutation *TweetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *TweetCreate) SetName(v string) *TweetCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetScreenName sets the "screen_name" field.
func (_c *TweetCreate) SetScreenName(v string) *TweetCreate {
	_c.mutation.SetScreenName(v)
	return _c
}

// SetFullText sets the "full_text" field.
func (_c *TweetCreate) SetFullText(v string) *TweetCreate {
	_c.mutation.SetFullText(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *TweetCreate) SetCreatedAt(v time.Time) *TweetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetPermanentURL sets the "permanent_url" field.
func (_c *TweetCreate) SetPermanentURL(v string) *TweetCreate {
	_c.mutation.SetPermanentURL(v)
	return _c
}

// SetRawJSON sets the "raw_json" field.
func (_c *TweetCreate) SetRawJSON(v string) *TweetCreate {
	_c.mutation.SetRawJSON(v)
	return _c
}

// SetSyncedAt sets the "synced_at" field.
func (_c *TweetCreate) SetSyncedAt(v time.Time) *TweetCreate {
	_c.mutation.SetSyncedAt(v)
	return _c
}

// SetBookmarked sets the "bookmarked" field.
func (_c *TweetCreate) SetBookmarked(v tweet.Bookmarked) *TweetCreate {
	_c.mutation.SetBookmarked(v)
	return _c
}

// SetRating sets the "rating" field.
func (_c *TweetCreate) SetRating(v int8) *TweetCreate {
	_c.mutation.SetRating(v)
	return _c
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_c *TweetCreate) SetNillableRating(v *int8) *TweetCreate {
	if v != nil {
		_c.SetRating(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TweetCreate) SetID(v string) *TweetCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_c *TweetCreate) AddMediumIDs(ids ...string) *TweetCreate {
	_c.mutation.AddMediumIDs(ids...)
	return _c
}

// AddMedia adds the "media" edges to the Media entity.
func (_c *TweetCreate) AddMedia(v ...*Media) *TweetCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMediumIDs(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_c *TweetCreate) Mutation() *TweetMutation {
	return _c.mutation
}

// Save creates the Tweet in the database.
func (_c *TweetCreate) Save(ctx context.Context) (*Tweet, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TweetCreate) SaveX(ctx context.Context) *Tweet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TweetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TweetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TweetCreate) defaults() {
	if _, ok := _c.mutation.Rating(); !ok {
		v := tweet.DefaultRating
		_c.mutation.SetRating(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TweetCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Tweet.name"`)}
	}
	if _, ok := _c.mutation.ScreenName(); !ok {
		return &ValidationError{Name: "screen_name", err: errors.New(`ent: missing required field "Tweet.screen_name"`)}
	}
	if _, ok := _c.mutation.FullText(); !ok {
		return &ValidationError{Name: "full_text", err: errors.New(`ent: missing required field "Tweet.full_text"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Tweet.created_at"`)}
	}
	if _, ok := _c.mutation.PermanentURL(); !ok {
		return &ValidationError{Name: "permanent_url", err: errors.New(`ent: missing required field "Tweet.permanent_url"`)}
	}
	if _, ok := _c.mutation.RawJSON(); !ok {
		return &ValidationError{Name: "raw_json", err: errors.New(`ent: missing required field "Tweet.raw_json"`)}
	}
	if _, ok := _c.mutation.SyncedAt(); !ok {
		return &ValidationError{Name: "synced_at", err: errors.New(`ent: missing required field "Tweet.synced_at"`)}
	}
	if _, ok := _c.mutation.Bookmarked(); !ok {
		return &ValidationError{Name: "bookmarked", err: errors.New(`ent: missing required field "Tweet.bookmarked"`)}
	}
	if v, ok := _c.mutation.Bookmarked(); ok {
		if err := tweet.BookmarkedValidator(v); err != nil {
			return &ValidationError{Name: "bookmarked", err: fmt.Errorf(`ent: validator failed for field "Tweet.bookmarked": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rating(); !ok {
		return &ValidationError{Name: "rating", err: errors.New(`ent: missing required field "Tweet.rating"`)}
	}
	if v, ok := _c.mutation.Rating(); ok {
		if err := tweet.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Tweet.rating": %w`, err)}
		}
	}
	return nil
}

func (_c *TweetCreate) sqlSave(ctx context.Context) (*Tweet, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Tweet.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TweetCreate) createSpec() (*Tweet, *sqlgraph.CreateSpec) {
	var (
		_node = &Tweet{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tweet.Table, sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(tweet.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.ScreenName(); ok {
		_spec.SetField(tweet.FieldScreenName, field.TypeString, value)
		_node.ScreenName = value
	}
	if value, ok := _c.mutation.FullText(); ok {
		_spec.SetField(tweet.FieldFullText, field.TypeString, value)
		_node.FullText = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tweet.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.PermanentURL(); ok {
		_spec.SetField(tweet.FieldPermanentURL, field.TypeString, value)
		_node.PermanentURL = value
	}
	if value, ok := _c.mutation.RawJSON(); ok {
		_spec.SetField(tweet.FieldRawJSON, field.TypeString, value)
		_node.RawJSON = value
	}
	if value, ok := _c.mutation.SyncedAt(); ok {
		_spec.SetField(tweet.FieldSyncedAt, field.TypeTime, value)
		_node.SyncedAt = value
	}
	if value, ok := _c.mutation.Bookmarked(); ok {
		_spec.SetField(tweet.FieldBookmarked, field.TypeEnum, value)
		_node.Bookmarked = value
	}
	if value, ok := _c.mutation.Rating(); ok {
		_spec.SetField(tweet.FieldRating, field.TypeInt8, value)
		_node.Rating = value
	}
	if nodes := _c.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Tweet.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TweetUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TweetCreate) OnConflict(opts ...sql.ConflictOption) *TweetUpsertOne {
	_c.conflict = opts
	return &TweetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Tweet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TweetCreate) OnConflictColumns(columns ...string) *TweetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TweetUpsertOne{
		create: _c,
	}
}

type (
	// TweetUpsertOne is the builder for "upsert"-ing
	//  one Tweet node.
	TweetUpsertOne struct {
		create *TweetCreate
	}

	// TweetUpsert is the "OnConflict" setter.
	TweetUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *TweetUpsert) SetName(v string) *TweetUpsert {
	u.Set(tweet.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TweetUpsert) UpdateName() *TweetUpsert {
	u.SetExcluded(tweet.FieldName)
	return u
}

// SetScreenName sets the "screen_name" field.
func (u *TweetUpsert) SetScreenName(v string) *TweetUpsert {
	u.Set(tweet.FieldScreenName, v)
	return u
}

// UpdateScreenName sets the "screen_name" field to the value that was provided on create.
func (u *TweetUpsert) UpdateScreenName() *TweetUpsert {
	u.SetExcluded(tweet.FieldScreenName)
	return u
}

// SetFullText sets the "full_text" field.
func (u *TweetUpsert) SetFullText(v string) *TweetUpsert {
	u.Set(tweet.FieldFullText, v)
	return u
}

// UpdateFullText sets the "full_text" field to the value that was provided on create.
func (u *TweetUpsert) UpdateFullText() *TweetUpsert {
	u.SetExcluded(tweet.FieldFullText)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TweetUpsert) SetCreatedAt(v time.Time) *TweetUpsert {
	u.Set(tweet.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TweetUpsert) UpdateCreatedAt() *TweetUpsert {
	u.SetExcluded(tweet.FieldCreatedAt)
	return u
}

// SetPermanentURL sets the "permanent_url" field.
func (u *TweetUpsert) SetPermanentURL(v string) *TweetUpsert {
	u.Set(tweet.FieldPermanentURL, v)
	return u
}

// UpdatePermanentURL sets the "permanent_url" field to the value that was provided on create.
func (u *TweetUpsert) UpdatePermanentURL() *TweetUpsert {
	u.SetExcluded(tweet.FieldPermanentURL)
	return u
}

// SetRawJSON sets the "raw_json" field.
func (u *TweetUpsert) SetRawJSON(v string) *TweetUpsert {
	u.Set(tweet.FieldRawJSON, v)
	return u
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *TweetUpsert) UpdateRawJSON() *TweetUpsert {
	u.SetExcluded(tweet.FieldRawJSON)
	return u
}

// SetSyncedAt sets the "synced_at" field.
func (u *TweetUpsert) SetSyncedAt(v time.Time) *TweetUpsert {
	u.Set(tweet.FieldSyncedAt, v)
	return u
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TweetUpsert) UpdateSyncedAt() *TweetUpsert {
	u.SetExcluded(tweet.FieldSyncedAt)
	return u
}

// SetBookmarked sets the "bookmarked" field.
func (u *TweetUpsert) SetBookmarked(v tweet.Bookmarked) *TweetUpsert {
	u.Set(tweet.FieldBookmarked, v)
	return u
}

// UpdateBookmarked sets the "bookmarked" field to the value that was provided on create.
func (u *TweetUpsert) UpdateBookmarked() *TweetUpsert {
	u.SetExcluded(tweet.FieldBookmarked)
	return u
}

// SetRating sets the "rating" field.
func (u *TweetUpsert) SetRating(v int8) *TweetUpsert {
	u.Set(tweet.FieldRating, v)
	return u
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *TweetUpsert) UpdateRating() *TweetUpsert {
	u.SetExcluded(tweet.FieldRating)
	return u
}

// AddRating adds v to the "rating" field.
func (u *TweetUpsert) AddRating(v int8) *TweetUpsert {
	u.Add(tweet.FieldRating, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Tweet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tweet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TweetUpsertOne) UpdateNewValues() *TweetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(tweet.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Tweet.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TweetUpsertOne) Ignore() *TweetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TweetUpsertOne) DoNothing() *TweetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TweetCreate.OnConflict
// documentation for more info.
func (u *TweetUpsertOne) Update(set func(*TweetUpsert)) *TweetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TweetUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TweetUpsertOne) SetName(v string) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateName() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateName()
	})
}

// SetScreenName sets the "screen_name" field.
func (u *TweetUpsertOne) SetScreenName(v string) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetScreenName(v)
	})
}

// UpdateScreenName sets the "screen_name" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateScreenName() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateScreenName()
	})
}

// SetFullText sets the "full_text" field.
func (u *TweetUpsertOne) SetFullText(v string) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetFullText(v)
	})
}

// UpdateFullText sets the "full_text" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateFullText() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateFullText()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TweetUpsertOne) SetCreatedAt(v time.Time) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateCreatedAt() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetPermanentURL sets the "permanent_url" field.
func (u *TweetUpsertOne) SetPermanentURL(v string) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetPermanentURL(v)
	})
}

// UpdatePermanentURL sets the "permanent_url" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdatePermanentURL() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdatePermanentURL()
	})
}

// SetRawJSON sets the "raw_json" field.
func (u *TweetUpsertOne) SetRawJSON(v string) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetRawJSON(v)
	})
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateRawJSON() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateRawJSON()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *TweetUpsertOne) SetSyncedAt(v time.Time) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateSyncedAt() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateSyncedAt()
	})
}

// SetBookmarked sets the "bookmarked" field.
func (u *TweetUpsertOne) SetBookmarked(v tweet.Bookmarked) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetBookmarked(v)
	})
}

// UpdateBookmarked sets the "bookmarked" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateBookmarked() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateBookmarked()
	})
}

// SetRating sets the "rating" field.
func (u *TweetUpsertOne) SetRating(v int8) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *TweetUpsertOne) AddRating(v int8) *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *TweetUpsertOne) UpdateRating() *TweetUpsertOne {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateRating()
	})
}

// Exec executes the query.
func (u *TweetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TweetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TweetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TweetUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: TweetUpsertOne.ID is not supported by MySQL driver. Use TweetUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TweetUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TweetCreateBulk is the builder for creating many Tweet entities in bulk.
type TweetCreateBulk struct {
	config
	err      error
	builders []*TweetCreate
	conflict []sql.ConflictOption
}

// Save creates the Tweet entities in the database.
func (_c *TweetCreateBulk) Save(ctx context.Context) ([]*Tweet, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Tweet, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TweetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TweetCreateBulk) SaveX(ctx context.Context) []*Tweet {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TweetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TweetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Tweet.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TweetUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *TweetCreateBulk) OnConflict(opts ...sql.ConflictOption) *TweetUpsertBulk {
	_c.conflict = opts
	return &TweetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Tweet.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TweetCreateBulk) OnConflictColumns(columns ...string) *TweetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TweetUpsertBulk{
		create: _c,
	}
}

// TweetUpsertBulk is the builder for "upsert"-ing
// a bulk of Tweet nodes.
type TweetUpsertBulk struct {
	create *TweetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Tweet.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(tweet.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TweetUpsertBulk) UpdateNewValues() *TweetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(tweet.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Tweet.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TweetUpsertBulk) Ignore() *TweetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TweetUpsertBulk) DoNothing() *TweetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TweetCreateBulk.OnConflict
// documentation for more info.
func (u *TweetUpsertBulk) Update(set func(*TweetUpsert)) *TweetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TweetUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *TweetUpsertBulk) SetName(v string) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateName() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateName()
	})
}

// SetScreenName sets the "screen_name" field.
func (u *TweetUpsertBulk) SetScreenName(v string) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetScreenName(v)
	})
}

// UpdateScreenName sets the "screen_name" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateScreenName() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateScreenName()
	})
}

// SetFullText sets the "full_text" field.
func (u *TweetUpsertBulk) SetFullText(v string) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetFullText(v)
	})
}

// UpdateFullText sets the "full_text" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateFullText() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateFullText()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *TweetUpsertBulk) SetCreatedAt(v time.Time) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateCreatedAt() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetPermanentURL sets the "permanent_url" field.
func (u *TweetUpsertBulk) SetPermanentURL(v string) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetPermanentURL(v)
	})
}

// UpdatePermanentURL sets the "permanent_url" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdatePermanentURL() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdatePermanentURL()
	})
}

// SetRawJSON sets the "raw_json" field.
func (u *TweetUpsertBulk) SetRawJSON(v string) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetRawJSON(v)
	})
}

// UpdateRawJSON sets the "raw_json" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateRawJSON() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateRawJSON()
	})
}

// SetSyncedAt sets the "synced_at" field.
func (u *TweetUpsertBulk) SetSyncedAt(v time.Time) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetSyncedAt(v)
	})
}

// UpdateSyncedAt sets the "synced_at" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateSyncedAt() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateSyncedAt()
	})
}

// SetBookmarked sets the "bookmarked" field.
func (u *TweetUpsertBulk) SetBookmarked(v tweet.Bookmarked) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetBookmarked(v)
	})
}

// UpdateBookmarked sets the "bookmarked" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateBookmarked() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateBookmarked()
	})
}

// SetRating sets the "rating" field.
func (u *TweetUpsertBulk) SetRating(v int8) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.SetRating(v)
	})
}

// AddRating adds v to the "rating" field.
func (u *TweetUpsertBulk) AddRating(v int8) *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.AddRating(v)
	})
}

// UpdateRating sets the "rating" field to the value that was provided on create.
func (u *TweetUpsertBulk) UpdateRating() *TweetUpsertBulk {
	return u.Update(func(s *TweetUpsert) {
		s.UpdateRating()
	})
}

// Exec executes the query.
func (u *TweetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TweetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TweetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TweetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
