// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"twitter-bookmarks-downloader/ent/media"
	"twitter-bookmarks-downloader/ent/predicate"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TweetUpdate is the builder for updating Tweet entities.
type TweetUpdate struct {
	config
	hooks    []Hook
	mutation *TweetMutation
}

// Where appends a list predicates to the TweetUpdate builder.
func (_u *TweetUpdate) Where(ps ...predicate.Tweet) *TweetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *TweetUpdate) SetName(v string) *TweetUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableName(v *string) *TweetUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScreenName sets the "screen_name" field.
func (_u *TweetUpdate) SetScreenName(v string) *TweetUpdate {
	_u.mutation.SetScreenName(v)
	return _u
}

// SetNillableScreenName sets the "screen_name" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableScreenName(v *string) *TweetUpdate {
	if v != nil {
		_u.SetScreenName(*v)
	}
	return _u
}

// SetFullText sets the "full_text" field.
func (_u *TweetUpdate) SetFullText(v string) *TweetUpdate {
	_u.mutation.SetFullText(v)
	return _u
}

// SetNillableFullText sets the "full_text" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableFullText(v *string) *TweetUpdate {
	if v != nil {
		_u.SetFullText(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TweetUpdate) SetCreatedAt(v time.Time) *TweetUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableCreatedAt(v *time.Time) *TweetUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPermanentURL sets the "permanent_url" field.
func (_u *TweetUpdate) SetPermanentURL(v string) *TweetUpdate {
	_u.mutation.SetPermanentURL(v)
	return _u
}

// SetNillablePermanentURL sets the "permanent_url" field if the given value is not nil.
func (_u *TweetUpdate) SetNillablePermanentURL(v *string) *TweetUpdate {
	if v != nil {
		_u.SetPermanentURL(*v)
	}
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *TweetUpdate) SetRawJSON(v string) *TweetUpdate {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableRawJSON(v *string) *TweetUpdate {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TweetUpdate) SetSyncedAt(v time.Time) *TweetUpdate {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableSyncedAt(v *time.Time) *TweetUpdate {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetBookmarked sets the "bookmarked" field.
func (_u *TweetUpdate) SetBookmarked(v tweet.Bookmarked) *TweetUpdate {
	_u.mutation.SetBookmarked(v)
	return _u
}

// SetNillableBookmarked sets the "bookmarked" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableBookmarked(v *tweet.Bookmarked) *TweetUpdate {
	if v != nil {
		_u.SetBookmarked(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *TweetUpdate) SetRating(v int8) *TweetUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TweetUpdate) SetNillableRating(v *int8) *TweetUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TweetUpdate) AddRating(v int8) *TweetUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_u *TweetUpdate) AddMediumIDs(ids ...string) *TweetUpdate {
	_u.mutation.AddMediumIDs(ids...)
	return _u
}

// AddMedia adds the "media" edges to the Media entity.
func (_u *TweetUpdate) AddMedia(v ...*Media) *TweetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediumIDs(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_u *TweetUpdate) Mutation() *TweetMutation {
	return _u.mutation
}

// ClearMedia clears all "media" edges to the Media entity.
func (_u *TweetUpdate) ClearMedia() *TweetUpdate {
	_u.mutation.ClearMedia()
	return _u
}

// RemoveMediumIDs removes the "media" edge to Media entities by IDs.
func (_u *TweetUpdate) RemoveMediumIDs(ids ...string) *TweetUpdate {
	_u.mutation.RemoveMediumIDs(ids...)
	return _u
}

// RemoveMedia removes "media" edges to Media entities.
func (_u *TweetUpdate) RemoveMedia(v ...*Media) *TweetUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TweetUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TweetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TweetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TweetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TweetUpdate) check() error {
	if v, ok := _u.mutation.Bookmarked(); ok {
		if err := tweet.BookmarkedValidator(v); err != nil {
			return &ValidationError{Name: "bookmarked", err: fmt.Errorf(`ent: validator failed for field "Tweet.bookmarked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := tweet.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Tweet.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *TweetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tweet.Table, tweet.Columns, sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tweet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScreenName(); ok {
		_spec.SetField(tweet.FieldScreenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullText(); ok {
		_spec.SetField(tweet.FieldFullText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tweet.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PermanentURL(); ok {
		_spec.SetField(tweet.FieldPermanentURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(tweet.FieldRawJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(tweet.FieldSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Bookmarked(); ok {
		_spec.SetField(tweet.FieldBookmarked, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(tweet.FieldRating, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(tweet.FieldRating, field.TypeInt8, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaIDs(); len(nodes) > 0 && !_u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TweetUpdateOne is the builder for updating a single Tweet entity.
type TweetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TweetMutation
}

// SetName sets the "name" field.
func (_u *TweetUpdateOne) SetName(v string) *TweetUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableName(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetScreenName sets the "screen_name" field.
func (_u *TweetUpdateOne) SetScreenName(v string) *TweetUpdateOne {
	_u.mutation.SetScreenName(v)
	return _u
}

// SetNillableScreenName sets the "screen_name" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableScreenName(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetScreenName(*v)
	}
	return _u
}

// SetFullText sets the "full_text" field.
func (_u *TweetUpdateOne) SetFullText(v string) *TweetUpdateOne {
	_u.mutation.SetFullText(v)
	return _u
}

// SetNillableFullText sets the "full_text" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableFullText(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetFullText(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TweetUpdateOne) SetCreatedAt(v time.Time) *TweetUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableCreatedAt(v *time.Time) *TweetUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPermanentURL sets the "permanent_url" field.
func (_u *TweetUpdateOne) SetPermanentURL(v string) *TweetUpdateOne {
	_u.mutation.SetPermanentURL(v)
	return _u
}

// SetNillablePermanentURL sets the "permanent_url" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillablePermanentURL(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetPermanentURL(*v)
	}
	return _u
}

// SetRawJSON sets the "raw_json" field.
func (_u *TweetUpdateOne) SetRawJSON(v string) *TweetUpdateOne {
	_u.mutation.SetRawJSON(v)
	return _u
}

// SetNillableRawJSON sets the "raw_json" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableRawJSON(v *string) *TweetUpdateOne {
	if v != nil {
		_u.SetRawJSON(*v)
	}
	return _u
}

// SetSyncedAt sets the "synced_at" field.
func (_u *TweetUpdateOne) SetSyncedAt(v time.Time) *TweetUpdateOne {
	_u.mutation.SetSyncedAt(v)
	return _u
}

// SetNillableSyncedAt sets the "synced_at" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableSyncedAt(v *time.Time) *TweetUpdateOne {
	if v != nil {
		_u.SetSyncedAt(*v)
	}
	return _u
}

// SetBookmarked sets the "bookmarked" field.
func (_u *TweetUpdateOne) SetBookmarked(v tweet.Bookmarked) *TweetUpdateOne {
	_u.mutation.SetBookmarked(v)
	return _u
}

// SetNillableBookmarked sets the "bookmarked" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableBookmarked(v *tweet.Bookmarked) *TweetUpdateOne {
	if v != nil {
		_u.SetBookmarked(*v)
	}
	return _u
}

// SetRating sets the "rating" field.
func (_u *TweetUpdateOne) SetRating(v int8) *TweetUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TweetUpdateOne) SetNillableRating(v *int8) *TweetUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TweetUpdateOne) AddRating(v int8) *TweetUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// AddMediumIDs adds the "media" edge to the Media entity by IDs.
func (_u *TweetUpdateOne) AddMediumIDs(ids ...string) *TweetUpdateOne {
	_u.mutation.AddMediumIDs(ids...)
	return _u
}

// AddMedia adds the "media" edges to the Media entity.
func (_u *TweetUpdateOne) AddMedia(v ...*Media) *TweetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMediumIDs(ids...)
}

// Mutation returns the TweetMutation object of the builder.
func (_u *TweetUpdateOne) Mutation() *TweetMutation {
	return _u.mutation
}

// ClearMedia clears all "media" edges to the Media entity.
func (_u *TweetUpdateOne) ClearMedia() *TweetUpdateOne {
	_u.mutation.ClearMedia()
	return _u
}

// RemoveMediumIDs removes the "media" edge to Media entities by IDs.
func (_u *TweetUpdateOne) RemoveMediumIDs(ids ...string) *TweetUpdateOne {
	_u.mutation.RemoveMediumIDs(ids...)
	return _u
}

// RemoveMedia removes "media" edges to Media entities.
func (_u *TweetUpdateOne) RemoveMedia(v ...*Media) *TweetUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMediumIDs(ids...)
}

// Where appends a list predicates to the TweetUpdate builder.
func (_u *TweetUpdateOne) Where(ps ...predicate.Tweet) *TweetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TweetUpdateOne) Select(field string, fields ...string) *TweetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Tweet entity.
func (_u *TweetUpdateOne) Save(ctx context.Context) (*Tweet, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TweetUpdateOne) SaveX(ctx context.Context) *Tweet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TweetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TweetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TweetUpdateOne) check() error {
	if v, ok := _u.mutation.Bookmarked(); ok {
		if err := tweet.BookmarkedValidator(v); err != nil {
			return &ValidationError{Name: "bookmarked", err: fmt.Errorf(`ent: validator failed for field "Tweet.bookmarked": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rating(); ok {
		if err := tweet.RatingValidator(v); err != nil {
			return &ValidationError{Name: "rating", err: fmt.Errorf(`ent: validator failed for field "Tweet.rating": %w`, err)}
		}
	}
	return nil
}

func (_u *TweetUpdateOne) sqlSave(ctx context.Context) (_node *Tweet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tweet.Table, tweet.Columns, sqlgraph.NewFieldSpec(tweet.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tweet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tweet.FieldID)
		for _, f := range fields {
			if !tweet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tweet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(tweet.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScreenName(); ok {
		_spec.SetField(tweet.FieldScreenName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FullText(); ok {
		_spec.SetField(tweet.FieldFullText, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(tweet.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.PermanentURL(); ok {
		_spec.SetField(tweet.FieldPermanentURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.RawJSON(); ok {
		_spec.SetField(tweet.FieldRawJSON, field.TypeString, value)
	}
	if value, ok := _u.mutation.SyncedAt(); ok {
		_spec.SetField(tweet.FieldSyncedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Bookmarked(); ok {
		_spec.SetField(tweet.FieldBookmarked, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(tweet.FieldRating, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(tweet.FieldRating, field.TypeInt8, value)
	}
	if _u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMediaIDs(); len(nodes) > 0 && !_u.mutation.MediaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MediaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tweet.MediaTable,
			Columns: []string{tweet.MediaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tweet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tweet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
