// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"
	"twitter-bookmarks-downloader/ent/tweet"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Tweet is the model entity for the Tweet schema.
type Tweet struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Author display name.
	Name string `json:"name,omitempty"`
	// ScreenName holds the value of the "screen_name" field.
	ScreenName string `json:"screen_name,omitempty"`
	// FullText holds the value of the "full_text" field.
	FullText string `json:"full_text,omitempty"`
	// Tweet publish time.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// PermanentURL holds the value of the "permanent_url" field.
	PermanentURL string `json:"permanent_url,omitempty"`
	// Source of truth; every other field is derived from it.
	RawJSON string `json:"raw_json,omitempty"`
	// SyncedAt holds the value of the "synced_at" field.
	SyncedAt time.Time `json:"synced_at,omitempty"`
	// Whether the tweet is currently on the bookmarks list (yes), was once but no longer is (formerly), or never was (no). Written only by capture flows.
	Bookmarked tweet.Bookmarked `json:"bookmarked,omitempty"`
	// Human judgment following Shotwell's model: -1 = rejected, 0 = unrated, 1-5 = stars. Written only by humans, never by capture flows.
	Rating int8 `json:"rating,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TweetQuery when eager-loading is set.
	Edges        TweetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TweetEdges holds the relations/edges for other nodes in the graph.
type TweetEdges struct {
	// Media holds the value of the media edge.
	Media []*Media `json:"media,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// MediaOrErr returns the Media value or an error if the edge
// was not loaded in eager-loading.
func (e TweetEdges) MediaOrErr() ([]*Media, error) {
	if e.loadedTypes[0] {
		return e.Media, nil
	}
	return nil, &NotLoadedError{edge: "media"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Tweet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tweet.FieldRating:
			values[i] = new(sql.NullInt64)
		case tweet.FieldID, tweet.FieldName, tweet.FieldScreenName, tweet.FieldFullText, tweet.FieldPermanentURL, tweet.FieldRawJSON, tweet.FieldBookmarked:
			values[i] = new(sql.NullString)
		case tweet.FieldCreatedAt, tweet.FieldSyncedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Tweet fields.
func (_m *Tweet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tweet.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case tweet.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case tweet.FieldScreenName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field screen_name", values[i])
			} else if value.Valid {
				_m.ScreenName = value.String
			}
		case tweet.FieldFullText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field full_text", values[i])
			} else if value.Valid {
				_m.FullText = value.String
			}
		case tweet.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case tweet.FieldPermanentURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field permanent_url", values[i])
			} else if value.Valid {
				_m.PermanentURL = value.String
			}
		case tweet.FieldRawJSON:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field raw_json", values[i])
			} else if value.Valid {
				_m.RawJSON = value.String
			}
		case tweet.FieldSyncedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field synced_at", values[i])
			} else if value.Valid {
				_m.SyncedAt = value.Time
			}
		case tweet.FieldBookmarked:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bookmarked", values[i])
			} else if value.Valid {
				_m.Bookmarked = tweet.Bookmarked(value.String)
			}
		case tweet.FieldRating:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rating", values[i])
			} else if value.Valid {
				_m.Rating = int8(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Tweet.
// This includes values selected through modifiers, order, etc.
func (_m *Tweet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMedia queries the "media" edge of the Tweet entity.
func (_m *Tweet) QueryMedia() *MediaQuery {
	return NewTweetClient(_m.config).QueryMedia(_m)
}

// Update returns a builder for updating this Tweet.
// Note that you need to call Tweet.Unwrap() before calling this method if this Tweet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Tweet) Update() *TweetUpdateOne {
	return NewTweetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Tweet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Tweet) Unwrap() *Tweet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Tweet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Tweet) String() string {
	var builder strings.Builder
	builder.WriteString("Tweet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("screen_name=")
	builder.WriteString(_m.ScreenName)
	builder.WriteString(", ")
	builder.WriteString("full_text=")
	builder.WriteString(_m.FullText)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("permanent_url=")
	builder.WriteString(_m.PermanentURL)
	builder.WriteString(", ")
	builder.WriteString("raw_json=")
	builder.WriteString(_m.RawJSON)
	builder.WriteString(", ")
	builder.WriteString("synced_at=")
	builder.WriteString(_m.SyncedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("bookmarked=")
	builder.WriteString(fmt.Sprintf("%v", _m.Bookmarked))
	builder.WriteString(", ")
	builder.WriteString("rating=")
	builder.WriteString(fmt.Sprintf("%v", _m.Rating))
	builder.WriteByte(')')
	return builder.String()
}

// Tweets is a parsable slice of Tweet.
type Tweets []*Tweet
