// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// Tweet is the predicate function for tweet builders.
type Tweet func(*sql.Selector)
